Nationalities = {
    'AUS': 'Australia',
    'AUT': 'Austria',
    'BEL': 'Belgium',
    'BRA': 'Brazil',
    'CAN': 'Canada',
    'CHN': 'China',
    'CZE': 'Czech Republic',
    'DEN': 'Denmark',
    'ESP': 'Spain',
    'FIN': 'Finland',
    'FRA': 'France',
    'GBR': 'Great Britain',
    'GER': 'Germany',
    'HUN': 'Hungary',
    'ITA': 'Italy',
    'JPN': 'Japan',
    'KOR': 'Korea',
    'NED': 'Netherlands',
    'NOR': 'Norway',
    'POL': 'Poland',
    'POR': 'Portugal',
    'RUS': 'Russia',
    'SUI': 'Switzerland',
    'SWE': 'Sweden',
    'TUR': 'Turkey',
    'USA': 'United States',
    'VEN': 'Venezuela',

}